workflows:
  build_and_deploy:
    name: Build and Deploy
    environment:
      node: 18.18
    scripts:
      - name: Install dependencies
        script: |
          npm install -g expo-cli@latest
          npm install
      - name: Check Expo CLI Installation
        script: |
          npx expo-cli --version
      - name: Build APK
        script: |
          npx expo-cli build:android --no-publish --non-interactive
      - name: Build AAB
        script: |
          npx expo-cli build:android --type app-bundle --no-publish --non-interactive
      - name: Deploy to Expo
        script: |
          npx expo-cli publish --non-interactive
    artifacts:
      - build/*.apk
      - build/*.aab