workflows:
  build_and_deploy:
    name: Build and Deploy
    environment:
      node: 18.18
    scripts:
      - name: Install dependencies
        script: |
          npm i -g expo-cli
          npm install
      - name: Check Expo CLI Installation
        script: |
          expo --version
      - name: Build APK
        script: |
          expo build:android --no-publish --non-interactive
      - name: Build AAB
        script: |
          expo build:android --type app-bundle --no-publish --non-interactive
      - name: Deploy to Expo
        script: |
          expo publish --non-interactive
    artifacts:
      - build/*.apk
      - build/*.aab