workflows:
  build_and_deploy:
    name: Build e deploy do app UpOnlineAFV
    scripts:
      - name: Instalar dependencias
        script: |
          npm install -g expo-cli
          npm install
      - name: Build APK
        script: |
          expo build:android --no-publish --non-interactive
      - name: Build AAB
        script: |
          expo build:android --type app-bundle --no-publish --non-interactive
      - name: Deploy no Expo
        script: |
          expo publish --non-interactive
    artifacts:
      - build/*.apk
      - build/*.aab